In [1]:
import pandas as pd
import numpy as np
import matplotlib

# Read and first look

In [2]:
df = pd.read_csv('data.csv', encoding='cp1251')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [3]:
df.info()
df.describe()
#df.shape

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [4]:
df.duplicated().sum()

np.int64(5268)

In [5]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

# Data clearing

In [6]:
df.drop_duplicates()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [7]:
df.dropna()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [8]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [9]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [10]:
df['InvoiceMonth'] = df['InvoiceDate'].dt.month
df['InvoiceDay'] = df['InvoiceDate'].dt.weekday
df['InvoiceHour'] = df['InvoiceDate'].dt.hour

In [11]:
df = df[df['UnitPrice'] > 0]
df = df[df['UnitPrice'] != 0]

In [12]:
df['TransactionType'] = df.apply(lambda row: 'return' if row['Quantity'] < 0 else 'sale', axis=1)
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceMonth,InvoiceDay,InvoiceHour,TransactionType
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,12,2,8,sale
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,2,8,sale
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,12,2,8,sale
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,2,8,sale
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,2,8,sale
...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,12,4,12,sale
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12,4,12,sale
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,12,4,12,sale
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,12,4,12,sale
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,12,4,12,sale

In [13]:
df['TotalRevenue'] = df['Quantity'] * df['UnitPrice']

In [14]:
df_returns = df[df['TransactionType'] == 'return'].copy()
df_sales = df[df['TransactionType'] == 'sale'].copy()

In [15]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceMonth,InvoiceDay,InvoiceHour,TransactionType,TotalRevenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,12,2,8,sale,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,2,8,sale,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,12,2,8,sale,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,2,8,sale,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,2,8,sale,20.34

# Data analysis

## Time analysis

In [16]:
month_revenue = df.groupby('InvoiceMonth')['TotalRevenue'].sum()
max_month = month_revenue.idxmax()
max_revenue_per_month = month_revenue.max()
print(f'best month: {pd.to_datetime(max_month, format='%m').month_name()}, max revenue: {max_revenue_per_month}')

best month: November, max revenue: 1461756.25

In [17]:
orders_per_week = df.groupby('InvoiceDay')['InvoiceNo'].nunique()
max_weekday = orders_per_week.idxmax()
max_orders_per_weekday = orders_per_week.max()
print(f'best weekday: {pd.to_datetime(max_weekday, format='%u').day_name()}, max orders: {max_orders_per_weekday}')

best weekday: Monday, max orders: 5217

## Product analysis

In [18]:
products_by_qty = df.groupby('StockCode')['Quantity'].sum()
products_by_qty.sort_values(ascending=False).head(10)

StockCode
22197     56450
84077     53847
85099B    47359
84879     36381
21212     36039
85123A    35082
23084     30680
22492     26437
22616     26111
21977     24753
Name: Quantity, dtype: int64

In [19]:
products_by_total_revenue = df.groupby('StockCode')['TotalRevenue'].sum()
products_by_total_revenue.sort_values(ascending=False).head(10)

StockCode
DOT       206245.48
22423     164762.19
47566      98302.98
85123A     97894.50
85099B     92356.03
23084      66756.59
POST       66230.64
22086      63791.94
84879      58959.73
79321      53768.06
Name: TotalRevenue, dtype: float64

In [20]:
df['StockCode'].nunique()

3938

In [21]:
avg_price = df_sales.groupby('StockCode')['UnitPrice'].mean()
avg_price.sort_values(ascending=False).head(10)

StockCode
B            11062.060000
AMAZONFEE     6880.545000
DOT            292.137068
M              230.860530
22827          158.076923
22828          156.428571
22656          146.750000
22655          143.421053
22823          118.076923
22826          114.024390
Name: UnitPrice, dtype: float64

## Client Analysis

In [22]:
df['CustomerID'].nunique()

4371

In [23]:
price_per_order = df.groupby(['CustomerID','InvoiceNo']).agg( TotalRevenue = ('TotalRevenue','sum'))
price_per_order
avg_price_per_order_by_customer = price_per_order.groupby('CustomerID')['TotalRevenue'].mean()
avg_price_per_order_by_customer.head(10)

CustomerID
12346.0       0.000000
12347.0     615.714286
12348.0     449.310000
12349.0    1757.550000
12350.0     334.400000
12352.0     140.491818
12353.0      89.000000
12354.0    1079.400000
12355.0     459.400000
12356.0     937.143333
Name: TotalRevenue, dtype: float64

In [24]:
clients_by_order_qty = df.groupby('CustomerID')['InvoiceNo'].nunique()
clients_by_order_qty.sort_values(ascending=False).head(10)

CustomerID
14911.0    248
12748.0    223
17841.0    169
14606.0    128
13089.0    118
15311.0    118
12971.0     89
14527.0     86
13408.0     81
16029.0     76
Name: InvoiceNo, dtype: int64

In [25]:
clients_by_purchases = df_sales.groupby('CustomerID')['TotalRevenue'].sum()
clients_by_purchases.sort_values(ascending=False).head(10)

CustomerID
14646.0    280206.02
18102.0    259657.30
17450.0    194550.79
16446.0    168472.50
14911.0    143825.06
12415.0    124914.53
14156.0    117379.63
17511.0     91062.38
16029.0     81024.84
12346.0     77183.60
Name: TotalRevenue, dtype: float64

## Geographical analysis

In [26]:
total_revenue_by_country = df.groupby('Country')['TotalRevenue'].sum()
total_revenue_by_country

Country
Australia                137077.270
Austria                   10154.320
Bahrain                     548.400
Belgium                   40910.960
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20086.290
Cyprus                    12946.290
Czech Republic              707.720
Denmark                   18768.140
EIRE                     263276.820
European Community         1291.750
Finland                   22326.740
France                   197403.900
Germany                  221698.210
Greece                     4710.520
Hong Kong                 10117.040
Iceland                    4310.000
Israel                     7907.820
Italy                     16890.510
Japan                     35340.620
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2505.470
Netherlands              284661.540
Norway                    35163.460
Poland                     7213.140
Portugal                  29367.020
RSA                        1002.310
Saudi Arabia                131.170
Singapore                  9120.390
Spain                     54774.580
Sweden                    36595.910
Switzerland               56385.350
USA                        1730.920
United Arab Emirates       1902.280
United Kingdom          8209930.484
Unspecified                4749.790
Name: TotalRevenue, dtype: float64

In [27]:
total_customers_by_country = df.groupby('Country')['CustomerID'].nunique()
total_customers_by_country

Country
Australia                  9
Austria                   11
Bahrain                    2
Belgium                   25
Brazil                     1
Canada                     4
Channel Islands            9
Cyprus                     8
Czech Republic             1
Denmark                    9
EIRE                       3
European Community         1
Finland                   12
France                    87
Germany                   95
Greece                     4
Hong Kong                  0
Iceland                    1
Israel                     4
Italy                     15
Japan                      8
Lebanon                    1
Lithuania                  1
Malta                      2
Netherlands                9
Norway                    10
Poland                     6
Portugal                  19
RSA                        1
Saudi Arabia               1
Singapore                  1
Spain                     31
Sweden                     8
Switzerland               21
USA                        4
United Arab Emirates       2
United Kingdom          3949
Unspecified                4
Name: CustomerID, dtype: int64

In [31]:
#price_per_order = df.groupby(['Country','InvoiceNo']).agg( TotalOrderRevenue = ('TotalRevenue','sum'))
avg_order_price_by_country = df.groupby(['Country','InvoiceNo']).agg( TotalOrderRevenue = ('TotalRevenue','sum')).groupby('Country')['TotalOrderRevenue'].mean()
avg_order_price_by_country

Country
Australia               1986.627101
Austria                  534.437895
Bahrain                  137.100000
Belgium                  343.789580
Brazil                  1143.600000
Canada                   611.063333
Channel Islands          608.675455
Cyprus                   647.314500
Czech Republic           141.544000
Denmark                  893.720952
EIRE                     731.324500
European Community       258.350000
Finland                  465.140417
France                   428.208026
Germany                  367.658723
Greece                   785.086667
Hong Kong                674.469333
Iceland                  615.714286
Israel                   878.646667
Italy                    307.100182
Japan                   1262.165000
Lebanon                 1693.880000
Lithuania                415.265000
Malta                    250.547000
Netherlands             2846.615400
Norway                   879.086500
Poland                   300.547500
Portugal                 413.620000
RSA                     1002.310000
Saudi Arabia              65.585000
Singapore                912.039000
Spain                    521.662667
Sweden                   795.563261
Switzerland              761.964189
USA                      247.274286
United Arab Emirates     634.093333
United Kingdom           383.803024
Unspecified              365.368462
Name: TotalOrderRevenue, dtype: float64

# Advanced analysis